### ISSUE TITLE
Multiply doesn't work properly with float types

### ISSUE THREAD

**Issue by dix75** [cerevra/int#13]
```
uint32_t b = 10;
b *= 2.5;    // 25
```

```
uint512_t a = 10;
a *= 2.5;   // 20
```
p.s. Maybe there are any problems with other operations

**Comment by cerevra** [comment]
You are right. Thank you
https://github.com/cerevra/int/commit/e38f0632bdf9a1769baf4a169a4a8ff8892311b0
