### ISSUE TITLE
Update testNativeOperator

### ISSUE THREAD

**Issue by dix75** [cerevra/int#14]
During whole the testNatibeOperator function there are a lot of  the same assert checking.
`assert(typeid(uint512_t) == typeid(a1), "");`

for instance (I've omitted some lines off)
```
        auto a1 = ~uint512_t(0xff);
        assert(typeid(uint512_t) == typeid(a1), "");
       ...
        assert(a1.m_arr[63] == 0x00, "");

        auto a2 = -uint512_t(0x1);
        assert(typeid(uint512_t) == typeid(a1), "");
       ...
```

**Comment by cerevra** [comment]
Thank you
https://github.com/cerevra/int/commit/23b1c3629ab4849c7a60e3af22cb21fbf3890190
