### ISSUE TITLE
shift_left() noexcept

### ISSUE THREAD

**Issue by 4ertus2** [cerevra/int#23]
`shift_left()` is called from `operator<<(const wide_integer<Bits, Signed>& lhs, int n) noexcept` but throws.

In fact there's no much reason to make shift_left throwing an error. There's no such exception for native interegs and result for `-x << n` is the same as for natives.

**Comment by cerevra** [comment]
Yes, it [throws](https://github.com/cerevra/int/blob/master/v3/impl.h#L285).
@apolukhin, there was some corner case for left shift with signed values. Could you pay attention to this issue?

**Comment by 4ertus2** [comment]
There's also an interesting question: does the library really need `noexcept` at all? https://stackoverflow.com/questions/21463119/does-it-make-sense-to-declare-inline-functions-noexcept

**Comment by alexey-milovidov** [comment]
We can remove the check - this is what "undefined behaviour" for.

**Comment by cerevra** [comment]
shift_left() doesn't throw any more

**Comment by cerevra** [comment]
@apolukhin
FYI
