### ISSUE TITLE
Ошибка в вычислении numeric_limits::digits10

### ISSUE THREAD

**Issue by Imp5** [cerevra/int#7]
Сейчас вычисляется как digits10 = digits * 38.2308
Должно вычисляться как digits10 = digits * 0.30102999566

**Comment by Imp5** [comment]
Ну и в самом digits похоже забыт sizeof(long)

**Comment by cerevra** [comment]
Спасибо. Починил
https://github.com/cerevra/int/commit/b2fd277500c2bb9d36221068932eb82f17739202
