### ISSUE TITLE
Swap

### ISSUE THREAD

**Issue by dix75** [cerevra/int#9]
What about the internal and external swap functions?

inline void swap(wide_integer<MachineWords, Signed> const& rhs) noexcept;
inline void swap(wide_integer<MachineWords, Signed> const& lhs. wide_integer<MachineWords, Signed> const& rhs) noexcept;

**Comment by cerevra** [comment]
std::swap() works correctly. I think it is anough

**Comment by cerevra** [comment]
I would like to notice: wide_int makes efforts to mimic interface of built-in type: int
